### PR TITLE
Added Haptic Feedback when Button is pressed on

### PR DESCRIPTION
**Pull request by heysaik**

### CODE REVIEW

**Comment by thePsguy** [comment]
Hey @theindiandev1065, thank you for the contribution!

Since not everyone might need haptic feedback out of the box, it would make more sense to have a variable, false by default, keeping track of this in the class. 
The haptic feedback could then only be generated if this `hapticEnabled` property is set to true on that object.

Once this change is made, I think this PR would be ready to merge.

**Comment by heysaik** [comment]
Alright Cool!

**Comment by heysaik** [comment]
Hey @thePsguy I added the hapticEnabled variable!

**Review by hemangshah — APPROVED** [review]

**Comment by thePsguy** [comment]
@theindiandev1065, I'm merging to a separate branch for now, and will merge to master soon. Thank you for the contribution!

**Pull request merged**
